AWSTemplateFormatVersion: "2010-09-09"

# ------------------------------------------------------------#
# Parameters
# ------------------------------------------------------------#
Parameters:
    Env:
        Description: "Environment of system"
        Type: String

    System:
        Description: "Name of system"
        Type: String

    SystemPrefix:
        Description: "Prefix of system"
        Type: String

    VpcId:
        Description: "ID of VPC"
        Type: String

    VpcCidr:
        Description: "CIDR of VPC"
        Type: String

    SubnetId:
        Description: "ID of Subnet"
        Type: String

# ------------------------------------------------------------#
    PrivateIPAddress:
        Description: "Private IP address of instance"
        Type: String

# ------------------------------------------------------------#
# SSM Parameter
# ------------------------------------------------------------#
    BetaSsmParameterOS:
        Description: "Image of instance(Latest of Windows_Server 2022)"
        Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
        Default: "/aws/service/ami-windows-latest/Windows_Server-2022-Japanese-Full-Base"
  
Resources:
# ------------------------------------------------------------#
# EC2 Instance
# ------------------------------------------------------------#
    BetaEC2InstanceWindows:
        Type: "AWS::EC2::Instance"
        DeletionPolicy: Delete
        Properties:
            ImageId: !Ref BetaSsmParameterOS
            InstanceType: "t2.medium"
            KeyName: !ImportValue ExportBetaEC2KeyPair
            AvailabilityZone: !Sub "${AWS::Region}a"
            Tenancy: "default"
            NetworkInterfaces:
              - AssociatePublicIpAddress: "true"
                DeviceIndex: "0"
                SubnetId: !Ref SubnetId
                GroupSet:
                 - !ImportValue ExportBetaEC2SecurityGroup
                PrivateIpAddress: !Ref PrivateIPAddress
            EbsOptimized: false
            SourceDestCheck: true
            BlockDeviceMappings: 
              - 
                DeviceName: "/dev/sda1"
                Ebs: 
                    Encrypted: false
                    VolumeSize: 30
                    VolumeType: "gp2"
                    DeleteOnTermination: true
            IamInstanceProfile: !ImportValue ExportBetaIAMInstanceProfile
            Tags: 
              - 
                Key: "System"
                Value: !Ref System
              - 
                Key: "Name"
                Value: !Sub ${SystemPrefix}-${Env}-ec2-windows
            HibernationOptions: 
                Configured: false
            EnclaveOptions: 
                Enabled: false
            UserData: 
                Fn::Base64: !Sub |
                    <powershell>
                    ## Installing choco.
                    Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
                    ## Install with user data.
                    choco install -y 7zip
                    choco install -y winscp
                    choco install -y teraterm
                    choco install -y vscode
                    choco install -y winmerge
                    choco install -y wireshark
                    choco install -y awscli
                    choco install -y sizer
                    choco install -y sakuraeditor
                    choco install -y googlechrome
                    choco install -y googlejapaneseinput
                    ## Install after OS installation.
                    #choco install -y git
                    #choco install -y nodejs --version=18.11.0
                    </powershell>

# ------------------------------------------------------------#
# Outputs
# ------------------------------------------------------------#
Outputs:
    ExportBetaEC2InstanceWindows:
        Value: !Ref BetaEC2InstanceWindows
        Export:
            Name: ExportBetaEC2InstanceWindows
